#!/bin/bash

set -e

if [ "$1" = "down" ]; then
  docker compose --file ./manifests/nam-box/docker-compose.dev.yaml down
else
  ./build -f local.docker-bake.hcl
  docker compose --file ./manifests/nam-box/docker-compose.dev.yaml up -d
fi
