x-common: &common
  platform: ${PLATFORM}

services:
  certs:
    <<: *common
    image: ghcr.io/rcwbr/nam-box/certs:local
    volumes:
      - /opt/nam-box/ssl/nam-box.local:/etc/nam-box/ssl
    environment:
      CN: nam-box.local
