x-common: &common
  platform: ${PLATFORM}

services:
  core:
    <<: *common
    image: ghcr.io/rcwbr/nam-box/core:local
    ipc: "shareable"
    devices:
      - "/dev/snd:/dev/snd"
    ports:
      - "8000:8000"
    volumes:
      - "/dev/snd:/dev/snd"
      - nam-state:/var/nam
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
      - IPC_LOCK
    security_opt:
      - seccomp=unconfined
    privileged: true
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/dev/shm/dbus-session
    shm_size: 700M
    ulimits:
      memlock: -1

  # jack-bazel:
  #   <<: *common
  #   image: ghcr.io/rcwbr/nam-box/jack-bazel:local
  #   ipc: "shareable"
  #   devices:
  #     - "/dev/snd:/dev/snd"
  #   cap_add:
  #     - SYS_NICE
  #     - SYS_RAWIO
  #     - IPC_LOCK
  #   security_opt:
  #     - seccomp=unconfined
  #   privileged: true
  #   environment:
  #     - DBUS_SESSION_BUS_ADDRESS=unix:path=/dev/shm/dbus-session
  #   shm_size: 700M
  #   ulimits:
  #     memlock: -1

  # nam-jalv:
  #   <<: *common
  #   image: ghcr.io/rcwbr/nam-box/nam-jalv:local
  #   depends_on:
  #     jack:
  #       condition: service_started
  #   ipc: "service:jack"
  #   volumes:
  #     - ./models:/usr/local/share/nam-models:ro
  #   shm_size: 700M
  #   working_dir: /home/nam
  #   command: ["sleep", "infinity"]
  #   user: root
  #   # command: ["jalv", "http://github.com/mikeoliphant/neural-amp-modeler-lv2"]
  #   environment:
  #     - LV2_PATH=/usr/local/lib/lv2
  #     - JACK_NO_AUDIO_RESERVATION=1
  #     - DBUS_SESSION_BUS_ADDRESS=unix:path=/dev/shm/dbus-session
  #   cap_add:
  #     - SYS_NICE
  #     - IPC_LOCK
  #   security_opt:
  #     - seccomp=unconfined
  #   ulimits:
  #     memlock: -1

volumes:
  nam-state:
