x-common: &common
  platform: ${PLATFORM}

services:
  effects:
    <<: *common
    image: ghcr.io/rcwbr/nam-box/effects:local
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "/dev/snd:/dev/snd"
      - effects-state:/var/mod
      - effects-models:/opt/nam/models
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
      - IPC_LOCK
    security_opt:
      - seccomp=unconfined
    privileged: true
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/dev/shm/dbus-session
      - JACKD_ARGS=${JACKD_ARGS}
    shm_size: 700M
    ulimits:
      memlock: -1
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.effects-strip.stripprefix.prefixes=/api/effects,/api/effects/"
      - "traefik.http.routers.effects.rule=PathPrefix(`/api/effects`)"
      - "traefik.http.routers.effects.middlewares=effects-strip"
      - "traefik.http.routers.effects.entrypoints=websecure"
      - "traefik.http.routers.effects.priority=100"
      - "traefik.http.routers.effects.service=effects@docker"
      - "traefik.http.services.effects.loadbalancer.server.port=80"
    networks:
      - proxy

  model:
    <<: *common
    image: ghcr.io/rcwbr/nam-box/files:local
    volumes:
      - effects-models:/opt/nam/models
    environment:
      FILE_BASE_DIR: /opt/nam/models
      FILE_EXTENSIONS: nam
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.model-strip.stripprefix.prefixes=/api/model,/api/model/"
      - "traefik.http.routers.model.rule=PathPrefix(`/api/model`)"
      - "traefik.http.routers.model.middlewares=model-strip"
      - "traefik.http.routers.model.entrypoints=websecure"
      - "traefik.http.routers.model.priority=100"
      - "traefik.http.routers.model.service=model@docker"
      - "traefik.http.services.model.loadbalancer.server.port=80"
    networks:
      - proxy

volumes:
  effects-models:
  effects-state:
