x-common: &common
  platform: ${PLATFORM}

services:
  bluetooth-host:
    <<: *common
    image: ghcr.io/rcwbr/nam-box/bluetooth-host:local
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - bluetooth-dbus:/var/run/dbus

  bluetooth-manager:
    <<: *common
    image: ghcr.io/rcwbr/nam-box/bluetooth-manager:local
    volumes:
      - bluetooth-dbus:/var/run/dbus
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    depends_on:
      bluetooth-host:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bluetooth-manager-strip.stripprefix.prefixes=/api/bluetooth-manager,/api/bluetooth-manager/"
      - "traefik.http.routers.bluetooth-manager.rule=PathPrefix(`/api/bluetooth-manager`)"
      - "traefik.http.routers.bluetooth-manager.middlewares=bluetooth-manager-strip"
      - "traefik.http.routers.bluetooth-manager.entrypoints=websecure"
      - "traefik.http.routers.bluetooth-manager.priority=100"
      - "traefik.http.routers.bluetooth-manager.service=bluetooth-manager@docker"
      - "traefik.http.services.bluetooth-manager.loadbalancer.server.port=8000"

    networks:
      - proxy

volumes:
  bluetooth-dbus:
