x-common: &common
  platform: ${PLATFORM}

services:
  bluetooth-manager:
    <<: *common
    image: nginx:alpine
    command: [ "nginx", "-g", "daemon off;"]
    expose:
      - "8000"
    volumes:
      - ./partials/bluetooth-mock.nginx.conf:/etc/nginx/conf.d/default.conf:ro
