#!/bin/bash
# git-worktree-hermes.sh — Create a git worktree from the bare mirror.
#
# Usage:
#   git-worktree-hermes.sh <branch-name> [worktree-base-dir]
#
# Creates a git worktree on a fresh branch from the
# redesigned-space-spork-state branch in the bare mirror at
# worktrees/upstream. Only tracked content (committed in the mirror)
# appears in the worktree. The mirror must already exist and contain
# the redesigned-space-spork-state branch.

set -euo pipefail

BRANCH_NAME="${1:-}"
WORKTREE_BASE="${2:-/workspace/worktrees}"
MIRROR_BASE="redesigned-space-spork-state"

if [ -z "$BRANCH_NAME" ]; then
  echo "Usage: $0 <branch-name> [worktree-base-dir]"
  exit 1
fi

# --- Resolve repo root ---
if [ -d "/workspace/.git" ]; then
  REPO_ROOT="/workspace"
else
  REPO_ROOT="$(pwd)"
  while [ ! -d "$REPO_ROOT/.git" ] && [ "$REPO_ROOT" != "/" ]; do
    REPO_ROOT="$(dirname "$REPO_ROOT")"
  done
  if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "❌ Not inside a git repository."
    exit 1
  fi
fi

# --- Use the bare mirror at worktrees/upstream ---
# The mirror must be pre-populated with the redesigned-space-spork-state
# branch. It is NOT created or synced by this script — only used as-is.
UPSTREAM="$REPO_ROOT/worktrees/upstream"
if [ ! -d "$UPSTREAM" ] || [ ! -f "$UPSTREAM/HEAD" ]; then
  echo "❌ Bare mirror not found at $UPSTREAM."
  echo "   Create it first from a repo with redesigned-space-spork-state:"
  echo "   git clone --bare <repo> $UPSTREAM"
  exit 1
fi

if ! git -C "$UPSTREAM" show-ref --verify --quiet "refs/heads/$MIRROR_BASE"; then
  echo "❌ Branch '$MIRROR_BASE' not found in mirror at $UPSTREAM."
  exit 1
fi
echo "🔄 Using bare mirror at $UPSTREAM (branch: $MIRROR_BASE)"

# --- Create worktree on fresh branch from mirror's redesigned-space-spork-state ---
WORKTREE_PATH="$WORKTREE_BASE/$BRANCH_NAME"
mkdir -p "$WORKTREE_BASE"

if git -C "$UPSTREAM" show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
  echo "⚠️  Branch '$BRANCH_NAME' exists in mirror — recreating."
  git -C "$UPSTREAM" worktree prune 2>/dev/null || true
  git -C "$UPSTREAM" branch -D "$BRANCH_NAME" 2>/dev/null || true
fi
[ -d "$WORKTREE_PATH" ] && git worktree remove "$WORKTREE_PATH" --force 2>/dev/null || rm -rf "$WORKTREE_PATH" 2>/dev/null || true
git -C "$UPSTREAM" worktree prune 2>/dev/null || true

echo "🌱 New worktree: $WORKTREE_PATH ($BRANCH_NAME)"
git -C "$UPSTREAM" worktree add -f -b "$BRANCH_NAME" "$WORKTREE_PATH" "$MIRROR_BASE"

# --- Compute Docker mount path ---
CODESPACE_MOUNT="${DEVCONTAINER_HOST_WORKSPACE_MOUNT:-/var/lib/docker/codespacemount/workspace/$(basename "$REPO_ROOT")}"
REL_PATH="${WORKTREE_PATH#$REPO_ROOT/}"
DOCKER_MOUNT_PATH="$CODESPACE_MOUNT/$REL_PATH"

# --- Port offsets (deterministic from branch name, 1-8) ---
OFFSET_CHAR=$(echo "$BRANCH_NAME" | grep -o '[a-z]' | head -1)
if [ -n "$OFFSET_CHAR" ]; then
  PORT_OFFSET=$(( (( $(printf '%d' "'$OFFSET_CHAR") - 96 ) % 8) + 1 ))
else
  PORT_OFFSET=1
fi
WEB_PORT=$((4322 + PORT_OFFSET))
MOCK_API_PORT=$((8001 + PORT_OFFSET))
PROJECT_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' '-' | sed 's/^-//;s/-$//')

# --- Generate .dev.env ---
cat > "$WORKTREE_PATH/.dev.env" <<EOF
# Auto-generated by git-worktree-hermes.sh
DOCKER_MOUNT_PATH=$DOCKER_MOUNT_PATH
PROJECT_NAME=$PROJECT_NAME
NODE_VERSION=22
WEB_PORT=$WEB_PORT
MOCK_API_PORT=$MOCK_API_PORT
EOF

# --- Patch astro.config.dev.mjs: proxy to Docker service name ---
PREACT_DST="$WORKTREE_PATH/services/web/preact"
if [ -f "$PREACT_DST/astro.config.dev.mjs" ]; then
  sed -i 's|http://127.0.0.1:8001|http://mock-api:8001|g' "$PREACT_DST/astro.config.dev.mjs"
  echo "🔧 Patched astro.config.dev.mjs → proxy to mock-api:8001"
fi

# --- Output ---
echo "WORKTREE_PATH=$WORKTREE_PATH"
echo "DOCKER_MOUNT_PATH=$DOCKER_MOUNT_PATH"
echo "BRANCH=$BRANCH_NAME"
echo "PROJECT_NAME=$PROJECT_NAME"
echo "WEB_PORT=$WEB_PORT"
echo "MOCK_API_PORT=$MOCK_API_PORT"
echo ""
echo "✅ Ready! Start dev stack:"
echo "   DOCKER_API_VERSION=1.43 docker compose \\"
echo "     -p $PROJECT_NAME \\"
echo "     -f $WORKTREE_PATH/services/web/preact/compose.preact-dev.yaml \\"
echo "     --env-file $WORKTREE_PATH/.dev.env up -d"
