services:
  jack:
    image: ghcr.io/rcwbr/nam-box-jack:local
    entrypoint: bash -c "dbus-daemon --session --fork --address=unix:path=/tmp/dbus-session && export DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-session && jackd -d dummy -r 48000 -p 128"
    network_mode: host
    shm_size: 384M
    privileged: true

  jacktrip-hub:
    image: jacktrip/jacktrip
    network_mode: host
    shm_size: 384M
    privileged: true
    environment:
      - JACKTRIP_OPTS=-S -t -z --hubpatch 4 --bufstrategy 4 -q auto
    depends_on:
      - jack

  jacktrip-client-test:
    image: jacktrip/jacktrip
    shm_size: 384M
    privileged: true
    network_mode: host
    command: -C 127.0.0.1 -B 4465 -P 4464 -n 2
    depends_on:
      - jacktrip-hub
