services:
  mod-host:
    image: mod-host:initial-services1
    entrypoint: sleep 100
  mod-ui:
    image: mod-ui:initial-services1
    ports:
      - "80:8888"
    pull_policy: never
    environment:
      - MOD_DEV_ENVIRONMENT=0
  bluetooth-host:
    image: nam-bluetooth:initial-services1
    entrypoint: sleep 100
  mdns:
    image: flungo/avahi@sha256:803451d0200610298d30d3151240f47c5de4d6558f6a3a36340692048cdf28e0
    environment:
      - SERVER_HOST_NAME=nam-box
    network_mode: host
