services:
  mod-host:
    image: mod-host@sha256:62c42f05a78f904ea013d8e9fac2444884a79d4dcf1b53911a6b5ff014aaa97b
    entrypoint: sleep 100
  mod-ui:
    image: mod-ui:latest
    ports:
      - "80:8888"
    pull_policy: never
    environment:
      - MOD_DEV_ENVIRONMENT=0
  bluetooth-host:
    image: nam-bluetooth:latest
    entrypoint: sleep 100
  mdns:
    image: flungo/avahi@sha256:803451d0200610298d30d3151240f47c5de4d6558f6a3a36340692048cdf28e0
    environment:
      - SERVER_HOST_NAME=nam-box
    network_mode: host
