#!/bin/bash

set -ex

export DEVCONTAINER_IMAGE=nam-box-devcontainer
export DEVCONTAINER_REGISTRY=ghcr.io/rcwbr
export DEVCONTAINER_DEFINITION_TYPE=bake
export DEVCONTAINER_INITIALIZE_PID=$PPID
devcontainer_definition_files_arr=(
  devcontainer-bake.hcl
  docker-client/devcontainer-bake.hcl
  zsh/devcontainer-bake.hcl
  tmux/devcontainer-bake.hcl
  cwd://.devcontainer/nam-box.hcl
  useradd/devcontainer-bake.hcl
  pre-commit/devcontainer-bake.hcl
  cwd://.devcontainer/devcontainer-bake.hcl
)
DEVCONTAINER_DEFINITION_FILES="${devcontainer_definition_files_arr[*]}"
export DEVCONTAINER_DEFINITION_FILES
export DEVCONTAINER_BUILD_ADDITIONAL_ARGS="remote_definition=https://github.com/rcwbr/dockerfile-partials.git#0.10.0"
# If an argument is passed to this script, pass it to the build call
if [[ -z $# ]]; then
  export DEVCONTAINER_BUILD_ADDITIONAL_ARGS="$DEVCONTAINER_BUILD_ADDITIONAL_ARGS $*"
fi
curl https://raw.githubusercontent.com/rcwbr/devcontainer-cache-build/0.8.0/devcontainer-cache-build-initialize | bash
