# HTTP server for static content
server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html/web;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html $uri/index.html =404;

        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "*";

        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header Referrer-Policy strict-origin-when-cross-origin;
    }
}