include:
  - path: ../partials/proxy.yaml
    project_directory: ..
    env_file: ../dev.env
  - path: ../partials/effects.yaml
    project_directory: ..
    env_file: ../dev.env
  # - path: ../partials/web.yaml
  #   project_directory: ..
  #   env_file: ../dev.env
  - path: ../partials/web-dev.yaml
    project_directory: ..
    env_file: ../dev.env

networks:
  proxy:
    name: proxy
    driver: bridge