#!/bin/bash

sudo service dbus start
sudo service bluetooth start

msg="Waiting for services to start..."
time=0
echo -n $msg
while [[ "$(pidof start-stop-daemon)" != "" ]]; do
    sleep 1
    time=$((time + 1))
    echo -en "\r$msg $time s"
done
echo -e "\r$msg done! (in $time s)"

sudo hciconfig hci0 down
sudo hciconfig hci0 up

# TODO bluetoothctl agent on

# Keep container running with bluetooth daemon
tail -f /dev/null
